### ISSUE TITLE
Url value for link is truncated

### ISSUE THREAD

**Issue by ramya-rao-a** [MicrosoftDocs/azure-docs-sdk-python#1081]
This is the [Key Vault overview page for Python packages](https://docs.microsoft.com/en-us/python/api/overview/azure/key-vault-index?view=azure-python)

Under `Version 1.1.x`, the reference link being used is https://docs.microsoft.com/en-us/python/api/overview/azure/keyvault?view=azure-python

The corresponding page in this repo is https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/key-vault-index.md where under `Version 1.1.x`, the reference link is https://docs.microsoft.com/python/api/overview/azure/keyvault?view=azure-python-previous

The `-previous` is somehow missing in the rendered page.

cc @scbedd, @mccoyp

Found in https://github.com/azure/azure-sdk-for-python/issues/15110

**Comment by mccoyp** [comment]
This is resolved in docs and will be rolled out from the `smoke-test` branch eventually, so this can be closed.
