### ISSUE TITLE
Issue with the argument enable_node_public_ip in the AmlCompute class of SDK v2

### ISSUE THREAD

**Issue by bhatsuchi08** [MicrosoftDocs/azure-docs-sdk-python#1677]
Link to the document - https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.entities.amlcompute?view=azure-python

I am trying to use the AML SDK v2 to create a compute cluster with the enable_node_public_ip=False.  This results in an error since it appears that this argument was not initialized in the code written for the AmlCompute class as highlighted in the screenshot below. Basically, irrespective of the value for enable_node_public_ip, using this argument explicitly results in a type error.

![image](https://user-images.githubusercontent.com/70103414/215099529-a38b06f2-4028-451a-b0df-4137b4b53e34.png)

**Comment by jhirono** [comment]
@bhatsuchi08 would you please make sure to use the latest SDK version? enable_node_public_ip parameter was added in the January release.
