### ISSUE TITLE
'Authenticate with token credentials' sample does not run as written

### ISSUE THREAD

**Issue by c-n-d** [MicrosoftDocs/azure-docs-sdk-python#32]
Hi,

Just wanted to check on one example from the [Authenticate with the Azure Management Libraries for Python](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-conceptual/python-sdk-azure-authenticate.md) doc. Running this sample generates the following error:

```bash
$ python adal_demo.py 
Traceback (most recent call last):
  File "adal_demo.py", line 11, in <module>
    context = adal.AuthenticationContext(LOGIN_ENDPOINT+TENANT)
NameError: name 'LOGIN_ENDPOINT' is not defined
```

If `LOGIN_ENDPOINT` and `TENANT` are capitalized for emphasis, please feel free to resolve this issue.

Thanks

**Comment by lmazuel** [comment]
The page is now fixed, thank you for the feedback @c-n-d !
