### ISSUE TITLE
Typo in pip command for PowerBI package

### ISSUE THREAD

**Issue by Gronan** [MicrosoftDocs/azure-docs-sdk-python#355]
https://docs.microsoft.com/en-us/python/api/overview/azure/power-bi?view=azure-python

> pip install azure-mgmt-powerblembedded

instead of 

> pip install azure-mgmt-powerbiembedded

**Comment by mmacy** [comment]
Confirmed fix has been published, closing. Thanks @Gronan and @CarolynOlsen!
