### ISSUE TITLE
Driver Value Doesn't work

### ISSUE THREAD

**Issue by dapolloxp** [MicrosoftDocs/azure-docs-sdk-python#395]
When trying to connect to SQL using the Python driver listed below, the connection fails

https://docs.microsoft.com/en-us/python/api/overview/azure/sql?view=azure-python#connect-to-a-sql-database

I have to use this format for it to connect

cnxn = pyodbc.connect('DRIVER={SQL Server};SERVER=localhost;DATABASE=testdb;UID=me;PWD=pass')

**Comment by erickson-doug** [comment]
@kraigb  -- can you investigate?

**Comment by kraigb** [comment]
@dapolloxp From what I can see, you're saying that DRIVER needs to be {SQL Server} rather than {ODBC Driver 13 for SQL Server}. Is that the case? It looks like everything else is the same, except that your format doesn't include PORT; perhaps that also isn't needed?
