### ISSUE TITLE
Install ADAL Doc reference

### ISSUE THREAD

**Issue by boykoc** [MicrosoftDocs/azure-docs-sdk-python#437]
[These docs](https://docs.microsoft.com/en-us/python/api/overview/azure/activedirectory?view=azure-python#client-library) reference installing ADAL with the following command:

`pip install azure-graphrbac`

And the sample code is different as well compared to most other docs, including the github repo's docs.  For instance, the [github repo shows](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki/ADAL-basics#installation):

`pip install adal` 

Is the difference due to outdated docs or different implementations or is graphrbac used for a different purpose?

**Comment by erickson-doug** [comment]
@sptramer @kraigb Please review this when you get a chance!

**Comment by sptramer** [comment]
@rloutlaw any guidance that you can provide for this, or a point of contact with SDK engineering who would give best practices advice? If we need to drop ADAL in favor of graph-rbac, a lot of docs might need edits.

**Comment by rloutlaw** [comment]
@sptramer My team doesn't own any of this overview content-just the generated reference docs for the SDKs. This all needs to updated to point to Python MSAL:

https://github.com/AzureAD/microsoft-authentication-library-for-python
