### ISSUE TITLE
Documentation refers to pydocumentdb not azure-cosmos

### ISSUE THREAD

**Issue by askpatrickw** [MicrosoftDocs/azure-docs-sdk-python#546]
https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/cosmosdb.md

Says to install pydocumentdb 

https://pypi.org/project/pydocumentdb/

🚨🚨🚨 The pydocumentdb package for versions 1.x and 2.x of the Azure Cosmos DB Python SDK for SQL API will be retired August 20, 2020. See the release and retirement documentation for more information.
Please use the latest version of the Python SDK with new package name, azure-cosmos.🚨🚨🚨

**Comment by lmazuel** [comment]
New spot:
https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/latest/cosmosdb.md

It has been fixed since
