### ISSUE TITLE
How to connect to existing database and\or collection

### ISSUE THREAD

**Issue by askpatrickw** [MicrosoftDocs/azure-docs-sdk-python#547]
The existing documentation and samples show how to create a client, a database and a collection, but they do not show the more common examples of how to work with existing data. How to: 
1. Create a client
2. Use client to connect to database\container
    - What is the difference?
    - Do you need to do both?
    - What is the format of a database_link or container_link? as in [azure.cosmos.container.container](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.container.container?view=azure-python), [azure.cosmos.cosmos_client.cosmosclient](https://docs.microsoft.com/en-us/python/api/azure-cosmos/azure.cosmos.cosmos_client.cosmosclient?view=azure-python#queryitems-database-or-container-link--query--options-none--partition-key-none-)
3. And from there... how to query, add, update and delete items

**Comment by askpatrickw** [comment]
Link formats:

    Database: f"dbs/{database_id}"
    Collection(Container): f"dbs/{database_id}/colls{container_id}"

While these say "_id" and that does match the Data Explorer UI, its not a GUID, its the name you gave the DB and Containers.

**Comment by askpatrickw** [comment]
This example shows how to connect the client and query a collection.

```python
from azure.cosmos import cosmos_client
import json

CONFIG = {
    "ENDPOINT": "ENDPOINT_FROM_YOUR_COSMOS_ACCOUNT",
    "PRIMARYKEY": "KEY_FROM_YOUR_COSMOS_ACCOUNT",
    "DATABASE": "DATABASE_ID",  # Prolly looks more like a name to you
    "CONTAINER": "YOUR_CONTAINER_ID"  # Prolly looks more like a name to you
}

CONTAINER_LINK = f"dbs/{CONFIG['DATABASE']}/colls/{CONFIG['CONTAINER']}"
FEEDOPTIONS = {}
FEEDOPTIONS["enableCrossPartitionQuery"] = True
# There is also a partitionKey Feed Option, but I was unable to figure out how to us it.

QUERY = {
    "query": f"SELECT * from c"
}

# Initialize the Cosmos client
client = cosmos_client.CosmosClient(
    url_connection=CONFIG["ENDPOINT"], auth={"masterKey": CONFIG["PRIMARYKEY"]}
)

# Query for some data
results = client.QueryItems(CONTAINER_LINK, QUERY, FEEDOPTIONS)

# Look at your data
print(list(results))

# You can also use the list as JSON
json.dumps(list(results), indent=4)
```

**Comment by lmazuel** [comment]
Since this issue was created, we released a complete revamping of this package, and this problem was adressed
