### ISSUE TITLE
Document is hidden

### ISSUE THREAD

**Issue by jesong** [MicrosoftDocs/azure-docs-sdk-python#552]
"https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring/" from "api/overview/azure/monitoring/index.md" in "https://github.com/MicrosoftDocs/MachineLearning-Python-pr/tree/live/Monitor" is hidden now. There is another document with higher priority will be shown. It is "https://docs.microsoft.com/en-us/python/api/overview/azure/monitoring" from "https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/live/docs-ref-services/monitoring.md". Considering changing file name or folder name to make "api/overview/azure/monitoring/index.md" in "https://github.com/MicrosoftDocs/MachineLearning-Python-pr/tree/live/Monitor" view-able.

**Comment by rloutlaw** [comment]
@jesong This is a common issue when different doc repos publish to the same shared namespace. 

I am open to a pull request with a suggested change for this along with the necessary TOC changes and redirection directives. 

Collisions are expected in this setup, and the content from this repo is the incumbent article by publish date. It is the responsibility of the contending content owner to correct the conflict.
