### ISSUE TITLE
Credentials objects are imported from azure.common.credentials but doc'd under msrestazure

### ISSUE THREAD

**Issue by kraigb** [MicrosoftDocs/azure-docs-sdk-python#632]
(From https://github.com/MicrosoftDocs/azure-dev-docs/issues/97)

In code (for example, what's shown on the [SDK authentication](https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate#mgmt-auth-token) page, and what's in the SDK test code), one uses statements like the following to import Credentials classes from azure.common.credentials:

`from azure.common.credentials import ServicePrincipalCredentials`

However, ServicePrincipalCredentials and other credentials classes don't appear in the [documentation for azure.common.credentials](https://docs.microsoft.com/en-us/python/api/azure-common/azure.common.credentials?view=azure-python). Instead, they're documented only under [msrestazure.azure_active_directory](https://docs.microsoft.com/en-us/python/api/msrestazure/msrestazure.azure_active_directory?view=azure-python).

It seems like these classes should appear in the reference under azure.common.credentials because that's there people will look for them based on the code.

**Comment by lmazuel** [comment]
We're now documenting authentication with `azure-identity`
