### ISSUE TITLE
Monitoring examples are outdated

### ISSUE THREAD

**Issue by estensen** [MicrosoftDocs/azure-docs-sdk-python#641]
[Azure Monitoring libraries for python](https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/master/docs-ref-services/monitoring.md) are outdated. `group_name` has been renamed to `resource_group_name` and there might be more.

Is this going to be fixed or is it possible to label examples like this as deprecated/outdated so people don't have to spend time working with examples that don't work?

**Comment by lmazuel** [comment]
I'm clsing this issue in favor of https://github.com/Azure/azure-sdk-for-python/issues/11271

**Comment by mukulgupta2138** [comment]
Hi @lmazuel Can you please reopen this issue ? It seems the linked issue is not yet updated.
