### ISSUE TITLE
query_entitities returns every row regardless of filter. 

### ISSUE THREAD

**Issue by grecoe** [MicrosoftDocs/azure-docs-sdk-python#937]
Using Python Function App with version azure-data-tables==12.0.0b1

- Retrieve TableClient by calling TableServiceClient.create_table_if_not_exists
- Build up filter 
```python
entity_query_value = "PartitionKey eq '{}'".format(self.partition_key)
```
- Call query
```python
            for found_entity in self.table_client.query_entities(
                filter=entity_query_value
            ):
```
First return.....found_entity['PartitionKey'] does not match the filter....in fact, the table has 2813 entries and no matter what I put in the filter I get 2813 return entities.

**Comment by seankane-msft** [comment]
Thank you for reporting this issue, this was fixed by [this issue](https://github.com/Azure/azure-sdk-for-python/issues/15094) and is available. You will need to update your package to the latest version via pipwhich can be done with:
```
pip install azure-data-tables==12.0.0b3
```
